name: Branch Naming Convention Check

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  branch-naming-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check branch naming convention
        run: |
          # Get the branch name
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          
          echo "Checking branch: $BRANCH_NAME"
          
          # Define allowed patterns based on naming conventions
          # feature/description, bugfix/description, hotfix/description, release/version
          if [[ $BRANCH_NAME =~ ^(feature|bugfix|hotfix|release|chore|docs|test|refactor)/.+ ]]; then
            echo "✅ Branch name '$BRANCH_NAME' follows naming conventions"
            exit 0
          else
            echo "❌ Branch name '$BRANCH_NAME' does not follow naming conventions"
            echo ""
            echo "Expected format: <type>/<description>"
            echo ""
            echo "Valid types:"
            echo "  - feature/  : New features or enhancements"
            echo "  - bugfix/   : Bug fixes"
            echo "  - hotfix/   : Critical bug fixes for production"
            echo "  - release/  : Release preparation"
            echo "  - chore/    : Maintenance tasks"
            echo "  - docs/     : Documentation updates"
            echo "  - test/     : Adding or updating tests"
            echo "  - refactor/ : Code refactoring"
            echo ""
            echo "Examples:"
            echo "  - feature/add-user-authentication"
            echo "  - bugfix/fix-login-error"
            echo "  - hotfix/security-patch"
            echo "  - release/v1.2.0"
            echo "  - chore/update-dependencies"
            echo "  - docs/update-readme"
            echo "  - test/add-unit-tests"
            echo "  - refactor/cleanup-code"
            echo ""
            echo "Please rename your branch to follow the convention."
            exit 1
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const issueComment = context.issue({
              body: `## ❌ Branch Naming Convention Violation
              
              The branch \`${branchName}\` does not follow the required naming conventions.
              
              **Expected format:** \`<type>/<description>\`
              
              **Valid types:**
              - \`feature/\` - New features or enhancements
              - \`bugfix/\` - Bug fixes  
              - \`hotfix/\` - Critical bug fixes for production
              - \`release/\` - Release preparation
              - \`chore/\` - Maintenance tasks
              - \`docs/\` - Documentation updates
              - \`test/\` - Adding or updating tests
              - \`refactor/\` - Code refactoring
              
              **Examples:**
              - \`feature/add-user-authentication\`
              - \`bugfix/fix-login-error\`
              - \`hotfix/security-patch\`
              - \`release/v1.2.0\`
              - \`chore/update-dependencies\`
              - \`docs/update-readme\`
              - \`test/add-unit-tests\`
              - \`refactor/cleanup-code\`
              
              Please rename your branch to follow the convention before merging.`
            });
            
            github.rest.issues.createComment(issueComment);
